config/routes.rb
Rails.application.routes.draw do
  root to: "voice#index"

  resources :voice
  post 'voice/:id' => 'voice#create'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animation.rb
class Animation < ApplicationRecord
  belongs_to :voice,optional: true, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voice.rb
class Voice < ApplicationRecord
  has_many :animations, :foreign_key => 'voice_id',dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/voice_controller.rb
class VoiceController < ApplicationController
  def index
    @voices = Voice.all
    @animations = Animation.all
    @voice  = Voice.find(1)
  end

  def show
    @voice = Voice.find(params[:id])
    @animations = Animation.where(voice_id: params[:id])
  end

  def new
    voice = Voice.new
    voice.animations.build
  end

  def create
    @voice = Voice.new(cvoice_params)
    @animation = @voice.animations.build(animation_params)
    #binding.pry
    @voice.save
    @animation.save
    redirect_to action: :index 
  end

  def edit
    @voice = Voice.find(params[:id])
  end

  def update
    voice = Voice.find(params[:id])
    voice.update(uvoice_params)
    redirect_to action: :index 
  end

  def destroy
    voice = Voice.find(params[:id])
    voice.destroy
    redirect_to action: :index 
  end

  private
  
  def cvoice_params
    params.permit(:name, :anime, :game, :other)
  end
  def uvoice_params
    params.require(:voice).permit(:id, :name, :anime, :game, :other)
  end

  def animation_params
    params.permit(:title).merge(voice_id: params[@voice.id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voice_helper.rb
module VoiceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/voice/edit.html.haml
編集画面

= form_with model: @voice, local: true do |f|
  = f.text_area :name, placeholder: "名前"
  = f.text_area :anime, placeholder: "出演アニメ"
  = f.text_area :game, placeholder: "出演ゲーム"
  = f.text_area :other, placeholder: "その他"
  = f.submit "更新", class: "btn"

= link_to '一覧画面に戻る', voice_index_path, class: "btn"

app/views/voice/index.html.haml
- @voices.each do |voice|
  .voice
    = link_to voice.name,voice
    - @animations.each do |animation|
      - if voice.id == animation.voice_id
        = animation.title
        - break
    = link_to '編集', edit_voice_path(voice), class: "btn"
    = link_to '削除', voice, method: :delete
= link_to '新規登録' , new_voice_path, class: "btn"

app/views/voice/new.html.haml
登録画面

= form_with model: @voice, local: true do |f|
  = f.label "名前"
  = f.text_area :name, placeholder: "名前"
  = f.text_area :anime, placeholder: "出演アニメ"
  = f.text_area :game, placeholder: "出演ゲーム"
  = f.text_area :other, placeholder: "その他"
  = f.text_area :title, placeholder: "その他出演アニメ"
  = f.submit "登録", class: "btn"

= link_to '一覧画面に戻る', voice_index_path, class: "btn"

app/views/voice/show.html.haml
詳細

.content
  = @voice.name
.content
  = @voice.anime
.content
  = @voice.game
.content
  = @voice.other
.content
  - @animations.each do |animation|
    = animation.title

= link_to '編集', edit_voice_path(@voice), class: "btn"
= link_to '削除', @voice, method: :delete

= link_to '一覧画面に戻る', voice_index_path, class: "btn"